// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	UserId int64 `json:"userid"`
	Token  Token `json:"token"`
}

type LoginRequest struct {
	Phone    string `json:"phone"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type LoginResponse struct {
	UserId int64 `json:"userid"`
	Token  Token `json:"token"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"userid"`
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Avatar   string `json:"avatar"`
}
