// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"github.com/sybapp/infoflow/applications/user/rpc/internal/logic"
	"github.com/sybapp/infoflow/applications/user/rpc/internal/svc"
	"github.com/sybapp/infoflow/applications/user/rpc/service"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *service.RegisterRequest) (*service.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *service.LoginRequest) (*service.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) FindById(ctx context.Context, in *service.FindByIdRequest) (*service.FindByIdResponse, error) {
	l := logic.NewFindByIdLogic(ctx, s.svcCtx)
	return l.FindById(in)
}

func (s *UserServer) FindByPhone(ctx context.Context, in *service.FindByPhoneRequest) (*service.FindByPhoneResponse, error) {
	l := logic.NewFindByPhoneLogic(ctx, s.svcCtx)
	return l.FindByPhone(in)
}

func (s *UserServer) FindByUsername(ctx context.Context, in *service.FindByUsernameRequest) (*service.FindByUsernameResponse, error) {
	l := logic.NewFindByUsernameLogic(ctx, s.svcCtx)
	return l.FindByUsername(in)
}
